services:
  minecraft-server-backup:
    image: ghcr.io/arian04/minecraft-server-backup:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        # image
        BUILDER_IMAGE: alpine
        BUILDER_IMAGE_TAG: 3.19
        RUNNER_IMAGE: alpine
        RUNNER_IMAGE_TAG: 3.19
