services:
  minecraft-server:
    image: ghcr.io/arian04/minecraft-server:$MC_JAR_TYPE-$MC_VERSION-latest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        # image
        BUILDER_IMAGE: python
        BUILDER_IMAGE_TAG: alpine3.19
        RUNNER_IMAGE: eclipse-temurin
        RUNNER_IMAGE_TAG: 17-jre-alpine
        # minecraft
        MC_JAR_TYPE: $MC_JAR_TYPE
        MC_VERSION: $MC_VERSION
