services:
  minecraft-server:
    image: ghcr.io/arian04/minecraft-server:${SERVER_IMAGE_TAG:?}
    networks:
      - minecraft
    env_file:
      - .env

    # If you want to change server ports, only edit the port number on the LEFT side of the colon
    ports:
      - "${EXTERNAL_SERVER_PORT:?}:25565"
      #- "25575:25575" # only uncomment if you really want to expose RCON to the network.

    # Allow you to 'docker attach' to the server to run commands in the server console
    stdin_open: true
    tty: true

    # Allows the processes within the container to increase their priority
    cap_add:
      - SYS_NICE

    volumes:
      - server-data:/data
    stop_grace_period: 120s
    restart: unless-stopped

  minecraft-backups:
    image: ghcr.io/arian04/minecraft-server-backup:${BACKUP_IMAGE_TAG:?}
    environment:
      # IMPORTANT: this must match the service name of the server container above
      RCON_TARGET: minecraft-server
    networks:
      - minecraft
    volumes:
      - server-data:/data:ro
      - server-backups:/backups
    stop_grace_period: 60s
    restart: unless-stopped

volumes:
  server-data:
  server-backups:

networks:
  minecraft:
