name: Create and publish MC server Docker images

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/minecraft-server

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        mc_jar_type:
          - fabric
          - purpur
          - paper
        mc_version:
          - 1.20.4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.mc_jar_type }}-${{ matrix.mc_version }}-latest
            type=raw,value=${{ matrix.mc_jar_type }}-${{ matrix.mc_version }}-{{sha}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILDER_IMAGE=python
            BUILDER_IMAGE_TAG=alpine3.19
            RUNNER_IMAGE=eclipse-temurin
            RUNNER_IMAGE_TAG=17-jre-alpine
            MC_JAR_TYPE=${{ matrix.mc_jar_type }}
            MC_VERSION=${{ matrix.mc_version }}
