name: Create and publish MC server Docker images

on:
  push:
    branches:
      - "main"
      - "ci"
    paths-ignore:
      - "**.md"

jobs:
  build-and-push-server-image:
    uses: ./.github/workflows/reusable-docker-compose-build-push.yml
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        mc_jar_type:
          - fabric
          - purpur
          - paper
        mc_version:
          - 1.20.4

    with:
      build_context: ./server
      build_args: |
        BUILDER_IMAGE=python
        BUILDER_IMAGE_TAG=alpine3.19
        RUNNER_IMAGE=eclipse-temurin
        RUNNER_IMAGE_TAG=17-jre-alpine
        MC_JAR_TYPE=${{ matrix.mc_jar_type }}
        MC_VERSION=${{ matrix.mc_version }}
      push_registry: ghcr.io
      push_image_name: ${{ github.repository_owner }}/minecraft-server
      push_image_tags_metadata: |
        type=raw,value=${{ matrix.mc_jar_type }}-${{ matrix.mc_version }}-latest
        type=raw,value=${{ matrix.mc_jar_type }}-${{ matrix.mc_version }}
        type=raw,value=${{ matrix.mc_jar_type }}-${{ matrix.mc_version }}-{{sha}}

  build-and-push-backup-image:
    uses: ./.github/workflows/reusable-docker-compose-build-push.yml
    permissions:
      contents: read
      packages: write

    with:
      build_context: ./backups
      build_args: |
        BUILDER_IMAGE=alpine
        BUILDER_IMAGE_TAG=3.19
        RUNNER_IMAGE=alpine
        RUNNER_IMAGE_TAG=3.19
      push_registry: ghcr.io
      push_image_name: ${{ github.repository_owner }}/minecraft-server-backup
      push_image_tags_metadata: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=raw,value={{sha}}
