on:
  workflow_call:
    inputs:
      # for building
      build_context:
        default: .
        type: string
      build_args:
        required: true
        type: string

      # for pushing
      push_registry:
        required: true
        type: string
      push_image_name:
        required: true
        type: string
      push_image_tags_metadata:
        required: true
        type: string

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ inputs.push_registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ inputs.push_registry }}/${{ inputs.push_image_name }}
          tags: ${{ inputs.push_image_tags_metadata }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: ${{ inputs.build_context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ inputs.build_args }}
